name: Sync to Hugging Face Spaces

on:
  push:
    branches: [huggingface] # Kích hoạt khi push code vào nhánh huggingface

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          SPACE_NAME: "ten-space-cua-ban" # Thay bằng tên Space của bạn
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add hf https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME
          
          # Đẩy nhánh 'huggingface' của GitHub vào nhánh 'main' của Hugging Face
          git push --force hf huggingface:main 
