name: Sync to Hugging Face Spaces

on:
  push:
    branches: [huggingface] # Kích hoạt tự động khi bạn push code vào nhánh huggingface

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          SPACE_NAME: "Compiler" # Đã chuẩn hóa theo đúng tên hiển thị trên giao diện của bạn
        run: |
          git config --global user.email "lmtcv1.9@gmail.com"
          git config --global user.name "hn"
          git remote add hf https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME
          
          # Đẩy mã nguồn từ nhánh phụ 'huggingface' của GitHub sang nhánh 'main' bắt buộc của Hugging Face
          git push --force hf huggingface:main
